version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "karlasgeir"
    reviewers:
      - "karlasgeir"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    assignees:
      - "karlasgeir"
    reviewers:
      - "karlasgeir"
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    assignees:
      - "karlasgeir"
    reviewers:
      - "karlasgeir"
