name: stalemate
description: A new Flutter package project.
version: 0.0.1
homepage:
repository: https://github.com/karlasgeir/stalemate
issue_tracker: https://github.com/karlasgeir/stalemate/issues

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: any
  build_runner: ^2.0.4
