// Mocks generated by Mockito 5.4.1 from annotations
// in stalemate/test/src/stalemate_refresher_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:stalemate/src/stalemate_loader/stalemate_loader.dart' as _i4;
import 'package:stalemate/src/stalemate_refresher/stalemate_refresh_config.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StaleMateRefreshConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaleMateRefreshConfig extends _i1.Mock
    implements _i3.StaleMateRefreshConfig {
  MockStaleMateRefreshConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration getNextRefreshDelay(DateTime? lastRefreshTime) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextRefreshDelay,
          [lastRefreshTime],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getNextRefreshDelay,
            [lastRefreshTime],
          ),
        ),
      ) as Duration);
  @override
  bool isStale(DateTime? lastRefreshTime) => (super.noSuchMethod(
        Invocation.method(
          #isStale,
          [lastRefreshTime],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [StaleMateLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockStaleMateLoader<T> extends _i1.Mock
    implements _i4.StaleMateLoader<T> {
  MockStaleMateLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Stream<T> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i2.Stream<T>.empty(),
      ) as _i2.Stream<T>);
  @override
  T get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.getter(#value),
        ),
      ) as T);
  @override
  _i2.Future<T> getLocalData() => (super.noSuchMethod(
        Invocation.method(
          #getLocalData,
          [],
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getLocalData,
                  [],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #getLocalData,
                [],
              ),
            ),
      ) as _i2.Future<T>);
  @override
  _i2.Future<T> getRemoteData() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteData,
          [],
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #getRemoteData,
                  [],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #getRemoteData,
                [],
              ),
            ),
      ) as _i2.Future<T>);
  @override
  _i2.Future<void> storeLocalData(T? data) => (super.noSuchMethod(
        Invocation.method(
          #storeLocalData,
          [data],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<void> removeLocalData() => (super.noSuchMethod(
        Invocation.method(
          #removeLocalData,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<void> addData(T? data) => (super.noSuchMethod(
        Invocation.method(
          #addData,
          [data],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<bool> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);
  @override
  _i2.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}
